HAI 1.2
  HOW IZ I SPARTACUS_SEARCH YR HAYSTACK AN YR NEEDLE
    IM IN YR LOOP UPPIN YR I TIL BOTH SAEM I AN 5
      VISIBLE HAYSTACK
    IM OUTTA YR LOOP
    FOUND YR HAYSTACK
  IF U SAY SO

  I HAS A HAY ITZ A BUKKIT
  HAY HAS A SRS 0 ITZ 1
  HAY HAS A SRS 1 ITZ 2
  HAY HAS A SRS 2 ITZ 3
  HAY HAS A SRS 3 ITZ 4
  HAY HAS A SRS 4 ITZ 5
  I IZ SPARTACUS_SEARCH YR HAY AN YR 3 MKAY
KTHXBYE
